### ISSUE TITLE
Parameter %baseDir% does not exist in config.neon

### ISSUE THREAD

**Issue by davidkregl** [stepansvoboda/resize#3]
Hi, 
I am not sure if it is just my fault or there does not exist %baseDir% parameter anymore. I have found a walk around by adding parameter baseDir to my parameters in config.neon and setting it to `%appDir%/../`.

I had to set the paremeter even if i do not use it in my configuration, which looks like this:
```yml
imageStore:
    storageDir: %tempDir%/uploads/
    cacheDir:   %wwwDir%/uploads/
    basePath:   /images/
```

I have also found out that changing the %baseDir% value in `Rostenkowski\ImageStore\Extension` to %appDir%/../ fixes the error.

> "nette/application": "^2.4"
> "php": ">7.0"
